[project]
name = "seleksi-ai-part-4"
version = "0.1.0"
description = "Task Reinforcement Learning for Artificial Intelligence Lab Assistant 2025"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "numpy>=2.3.2",
]
